title: BDSpyrunner
lang: en
description: BDSpyrunner is a plugin loader for BDS (Bedrock Dedicated Server).

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock